# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [11]:
# Given:

def func (a):
  temp = 0
  for i in range (len (a)):
    if i == 0:
      temp = a [0]
    if i + 1 == len (a):
      if a [i] == temp:
        return True
  return False



numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

print (func (numbers_x))
print (func (numbers_y))

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

True
False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [1]:
#code here
import numpy as np

a = np.array ([1, 2, 3, 4, 5])
b = np.array ([6, 7, 8, 9, 10])

add = a + b
product = a * b

print (add)
print (product)

[ 7  9 11 13 15]
[ 6 14 24 36 50]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [27]:
#code here

a = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape (3, 4)

print ("Reshaped: " + str (b))

c = np.array ([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

print (np.concatenate ((a, c), axis = 0, out=None, dtype=None, casting="same_kind"))
print (np.vstack ((a, c)))

Reshaped: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [33]:
#Code here

shopping_cart = []
print ("Welcome to my store")

while True:
  print ("1. Milk")
  print ("2. Chocolate")
  print ("3. Snack")

  i = input ("Enter your choice: ")

  if i == 'q':
    break

  if int (i) == 1:
    shopping_cart.append ("Milk")
    print ("Product added successfully")
  elif int (i) == 2:
    shopping_cart.append ("Chocolate")
    print ("Product added successfully")
  elif int (i) == 3:
    shopping_cart.append ("Snack")
    print ("Product added successfully")
  else:
    print ("Invalid input entered.")

print ("Contents of your shopping cart are: ")
print (shopping_cart)
print ("Thank You for shopping! See you soon.")


Welcome to my store
1. Milk
2. Chocolate
3. Snack
Enter your choice: 1
Product added successfully
1. Milk
2. Chocolate
3. Snack
Enter your choice: 5
Invalid input entered.
1. Milk
2. Chocolate
3. Snack
Enter your choice: q
Contents of your shopping cart are: 
['Milk']
Thank You for shopping! See you soon.


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [40]:
#code here

def classify_emails (s):
  important = []
  promotion = []
  spam = []

  for a in s:
    if "importance" in a or "important" in a:
      important.append (a)
    if "promotion" in a or "deals" in a:
      promotion.append (a)
    if "please" in a or "free" in a:
      spam.append (a)

  return important, promotion, spam

i = ["this is very important", "we have promotion for you", "please ignore"]
print (classify_emails (i))



(['this is very important'], ['we have promotion for you'], ['please ignore'])


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [41]:
#code here

trans = {
    "Hello" : "Hola",
    "Goodbye" : "Adios",
    "Thank you" : "Gracias",
    "Please" : "Por favor",
    "Yes" : "Si",
    "Of course" : "Claro",
    "No" : "No",
    "Love" : "Amor"
}

i = input ("Enter english word: ")

for a, b in trans.items ():
  if i == a:
    print ("Translation is: " + str (b))

Enter english word: Hello
Translation is: Hola


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [42]:
#code here

import pandas as pd

df = pd.read_csv ("https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv")
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [72]:
add = df ["Global_Sales"].sum ()
add

8920.44

In [47]:
highest = 0

for i in df ["Global_Sales"]:
  if i > highest:
    highest = i

highest

82.74

In [50]:
print ("NA Sales " + str (df ["NA_Sales"].mean ()))
print ("EU Sales " + str (df ["EU_Sales"].mean ()))
print ("JP Sales " + str (df ["JP_Sales"].mean ()))
print ("Other Sales " + str (df ["Other_Sales"].mean ()))

NA Sales 0.26466742981082064
EU Sales 0.14665200626581515
JP Sales 0.077781660441017
Other Sales 0.0480630196409206


In [95]:
a = df.groupby ("Genre")["Global_Sales"].sum ()
a = a.sort_values (ascending = False)
a.head ()

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [98]:
a = df.groupby ("Genre")["NA_Sales"].sum ()

a = a.sort_values (ascending = False)

print (a)
print (df.groupby ("Genre")["EU_Sales"].sum ())
print (df.groupby ("Genre")["JP_Sales"].sum ())
print (df.groupby ("Genre")["Other_Sales"].sum ())

a.head (1)

Genre
Action          877.83
Sports          683.35
Shooter         582.60
Platform        447.05
Misc            410.24
Racing          359.42
Role-Playing    327.28
Fighting        223.59
Simulation      183.31
Puzzle          123.78
Adventure       105.80
Strategy         68.70
Name: NA_Sales, dtype: float64
Genre
Action          525.00
Adventure        64.13
Fighting        101.32
Misc            215.98
Platform        201.63
Puzzle           50.78
Racing          238.39
Role-Playing    188.06
Shooter         313.27
Simulation      113.38
Sports          376.85
Strategy         45.34
Name: EU_Sales, dtype: float64
Genre
Action          159.95
Adventure        52.07
Fighting         87.35
Misc            107.76
Platform        130.77
Puzzle           57.31
Racing           56.69
Role-Playing    352.31
Shooter          38.28
Simulation       63.70
Sports          135.37
Strategy         49.46
Name: JP_Sales, dtype: float64
Genre
Action          187.38
Adventure        16.81
Fighting 

Genre
Action    877.83
Name: NA_Sales, dtype: float64

In [52]:
df.tail (10)

Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [99]:
a = df.groupby ("Platform")["Global_Sales"].sum ()
a = a.sort_values (ascending = False)
a.head (3)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [78]:
s = df.groupby ("Genre")["Global_Sales"].sum ()
per = []
for i in range (len (s)):
  per.append (s [i] / add * 100)

per

[19.63109443031958,
 2.6796884458614145,
 5.0323750846370805,
 9.079821174740259,
 9.319831757177896,
 2.7459407831900666,
 8.206321661263345,
 10.396011855917422,
 11.629134885723124,
 4.396644111725431,
 14.920003945993695,
 1.9631318634506818]

In [66]:
df ["NA_Sales"].corr (df ["EU_Sales"])

0.7677267483702631